#!/bin/bash

#============= Installing dependencies ================
echo ubuntu | sudo apt -y update 
sudo apt -y upgrade
sudo apt -y install git subversion cmake nano wget net-tools
#======================================================

#=========== Installing kernel modules ================
sudo apt -y install linux-headers-$(uname -r)
#======================================================


#==================== Permissions =====================
cd $HOME
sudo chmod 7777 -R du/
sudo chmod +x -R du/
cd du
#======================================================

#======================== UE ==========================
cp  ue openair3/NAS/TOOLS/ue_eurecom_test_sfr.conf
#======================================================

#================== Building OAI ======================
source du_build
#======================================================

#================= Configuring OAI ====================
source du_conf
#======================================================

#============ Initialize the NAS UE Layer =============
cd ~/openairinterface5g/cmake_targets/tools
source init_nas_s1 UE
#======================================================


