#!/bin/bash
source du_params
#cloning conf files
mkdir ~/openairinterface5g/ci-scripts/conf_files/du
cp ~/openairinterface5g/ci-scripts/conf_files/ue.nfapi.conf ~/openairinterface5g/ci-scripts/conf_files/du
PREFIX='~/openairinterface5g/ci-scripts/conf_files/du/ue.nfapi.conf'

#================ Configuring L1 ==================
sed -i '/local_n_if_name/c\	local_n_if_name  = "'$local_n_if_name'";' $PREFIX
sed -i '/remote_n_address/c\	remote_n_address = "'$remote_n_address'";' $PREFIX
sed -i '/local_n_address/c\	local_n_address = "'$local_n_address'";' $PREFIX
#======================================================
